# Preset  Device                      Percent
Low       backlight:intel_backlight        65
Low       ddc:i2c-18                       80

Medium    backlight:intel_backlight        85
Medium    ddc:i2c-18                       95

High      backlight:intel_backlight        90
High      ddc:i2c-18                      100

Max       backlight:intel_backlight       100
Max       ddc:i2c-18                      100