#!/usr/bin/env bash

# Remove desktop entries generated by desktop-entries/update.sh.

set -u

data_home=${XDG_DATA_HOME:-"$HOME/.local/share"}
applications_dir="$data_home/applications"

die() {
  printf 'delete-desktop-entries: %s\n' "$*" >&2
  exit 1
}

[ -d "$applications_dir" ] || exit 0

shopt -s nullglob
desktop_files=("$applications_dir"/launch-group-*.desktop)
for desktop_file in "${desktop_files[@]}"; do
  rm -f -- "$desktop_file" ||
    die "could not remove desktop entry: $desktop_file"
  printf 'removed %s\n' "$desktop_file"
done

if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$applications_dir" >/dev/null ||
    die "could not update desktop database"
fi